#!/usr/bin/env python
"""Phase 1 CLI — generate silver trajectories.

Wraps :func:`kgproweight.training.phase1_distill.run_phase1`. The script
ensures the Teacher receives *real* RRF top-50 retrieved passages
(bug-fix #4) by instantiating a FlashRAG hybrid retriever before
calling the Teacher.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path
from typing import Any, Dict, List

from kgproweight.config import ProjectConfig, load_config
from kgproweight.config.schemas import SilverDataConfig
from kgproweight.data.flashrag_loader import flashrag_config
from kgproweight.kg.entity_linker import EntityLinker
from kgproweight.kg.wikidata_retriever import WikidataSubgraphRetriever
from kgproweight.reward.prm_annotator import PRMAnnotator
from kgproweight.retrieval.bootstrap import resolve_entity_cache_path, resolve_kg_cache_dir
from kgproweight.retrieval.hybrid import DEFAULT_TOPK, build_flashrag_config
from kgproweight.training.phase1_distill import (
    Phase1Config,
    StratifiedSilverFilter,
    TeacherClient,
    phase1_candidate_path,
    run_phase1,
)
from kgproweight.utils.flashrag_bootstrap import setup_flashrag
from kgproweight.utils.logging import configure_logging, get_logger
from kgproweight.utils.paths import data_dir
from kgproweight.utils.seed import set_seed

configure_logging("INFO")
logger = get_logger(__name__)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--config", default=None, help="YAML config (see configs/training/phase1_silver.yaml).")
    p.add_argument("--dataset", default="hotpotqa")
    p.add_argument("--split", default="train")
    p.add_argument("--max_queries", type=int, default=None)
    p.add_argument("--max_workers", type=int, default=8)
    # 2026-08-22 (retraining_plan §11): default removed. It read
    # "deepseek-v4-flash", but that value is only reachable in the no---config
    # branch (:148 below), and every real silver run passes --config, so ALL
    # 24,998 silver trajectories were generated by configs' `deepseek-chat`.
    # The unreachable default is what put "deepseek-v4-flash" into the docs as
    # the teacher. None => the no-config branch now fails loudly instead.
    p.add_argument("--teacher", default=None,
                   help="Teacher model id. IGNORED when --config is given (the "
                        "config's training.silver_data.teacher_model wins); "
                        "required otherwise.")
    p.add_argument("--teacher_backend", choices=["openai", "deepseek"], default="deepseek")
    p.add_argument("--temperature", type=float, default=0.3)
    p.add_argument("--output", default=None)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--resume", action="store_true", help="Skip ids already present in the output file.")
    p.add_argument(
        "--sample_strategy", choices=["first", "random"], default="first",
        help="How to choose max_queries from the source split. Formal rebuilds "
             "and pilots should use deterministic random sampling; 'first' is "
             "kept only for backward-compatible reproduction.",
    )
    p.add_argument(
        "--offline",
        choices=["auto", "on", "off"],
        default="auto",
        help="KG/entity lookups: 'on'=cache-only (no Wikidata, misses return empty instantly); "
        "'off'=always call Wikidata; 'auto'=probe once and pick (default).",
    )
    p.add_argument("--rerank", type=int, default=0,
                   help="Enable cross-encoder rerank after RRF (e.g. --rerank 10)")
    p.add_argument(
        "--bridge_mode",
        choices=["off", "additive_v3"],
        default=None,
        help="Experimental Phase-1 bridge fusion; default comes from config and is off.",
    )
    p.add_argument("--allow_eval_split", action="store_true",
                   help="Acknowledge generating silver data from a dev/test split "
                        "(pipeline smoke tests only — output must NOT be trained on).")
    return p.parse_args()


def _build_retriever(dataset_name: str, topk: int = DEFAULT_TOPK):
    """Build a FlashRAG hybrid retriever (RRF top-K)."""
    setup_flashrag()
    from flashrag.utils import get_retriever

    flashrag_cfg = build_flashrag_config(
        dataset_name=dataset_name,
        save_note="phase1_silver",
        save_dir=str(data_dir() / "silver_data" / "_runtime"),
        split="train",
        topk=topk,
    )
    cfg = flashrag_config(flashrag_cfg)
    return get_retriever(cfg)


EVAL_SPLITS = {"dev", "test", "validation", "val"}


def _check_split_leakage(dataset_name: str, split: str, allow: bool) -> None:
    """Refuse to distil training data out of an evaluation split.

    The R9 v6 silver rerun was launched with ``--split dev``, so 48/50 and 50/50
    of the regenerated trajectories were HotpotQA dev questions — the exact set
    EM/F1 is reported on. Training on them makes any improvement unverifiable.
    (Note the three datasets' dev.jsonl and test.jsonl are byte-identical here,
    so "test" is not a safe alternative either.)
    """
    if split.lower() not in EVAL_SPLITS:
        return
    msg = (
        f"--split {split!r} is an EVALUATION split for {dataset_name}. Generating silver "
        f"training data from it leaks the eval set into training and invalidates the "
        f"reported EM/F1. Use --split train. If this is a deliberate throwaway "
        f"pipeline smoke test, pass --allow_eval_split and do NOT train on the output."
    )
    if not allow:
        raise SystemExit(f"REFUSING: {msg}")
    logger.warning("EVAL-SPLIT LEAKAGE ACKNOWLEDGED: %s", msg)


def _select_items(
    items: List[Dict[str, Any]], max_queries: int, strategy: str, seed: int
) -> List[Dict[str, Any]]:
    """Select a stable source subset before applying resume filtering."""
    if max_queries >= len(items):
        return list(items)
    if strategy == "first":
        return items[:max_queries]
    if strategy == "random":
        return random.Random(seed).sample(items, max_queries)
    raise ValueError(f"Unknown sample strategy: {strategy!r}")


def _load_items(
    dataset_name: str,
    split: str,
    max_queries: int,
    resume_path: Path | None = None,
    *,
    sample_strategy: str = "first",
    seed: int = 42,
) -> List[Dict[str, Any]]:
    src = Path(data_dir()) / dataset_name / f"{split}.jsonl"
    if not src.exists():
        raise FileNotFoundError(f"{src} missing — run scripts/prepare/03_download_datasets.py")
    seen_ids: set[str] = set()
    if resume_path and resume_path.exists():
        with open(resume_path, "r", encoding="utf-8") as fh:
            for line in fh:
                try:
                    obj = json.loads(line)
                    qid = str(obj.get("qid") or obj.get("id") or "")
                    if qid:
                        seen_ids.add(qid)
                except json.JSONDecodeError:
                    continue
        logger.info("Resume: skipping %d already-processed ids", len(seen_ids))

    items: List[Dict[str, Any]] = []
    with open(src, "r", encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            qid = str(obj.get("id", ""))
            items.append(obj)
    selected = _select_items(items, max_queries, sample_strategy, seed)
    # Select FIRST, then remove completed ids. Otherwise a resumed random run
    # draws a different subset and is no longer the same experiment.
    return [obj for obj in selected if str(obj.get("id") or obj.get("qid") or "") not in seen_ids]


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    _check_split_leakage(args.dataset, args.split, args.allow_eval_split)

    if args.config:
        cfg = load_config(args.config, validate=ProjectConfig)
        silver = cfg.training.silver_data
        teacher_model = silver.teacher_model
        teacher_backend = silver.teacher_backend
        temperature = silver.teacher_temperature
        max_queries = args.max_queries if args.max_queries is not None else silver.max_queries
        max_workers = silver.max_workers
        out_path = args.output or silver.output_path or str(Path(data_dir()) / "silver_data" / "silver_trajectories.jsonl")
        # Stratified acceptance: bucket by KG density with quotas instead of
        # hard-rejecting low-coverage/low-triple-rate traces, so the α-gate sees
        # genuine α→0 fallback examples. Only step bounds map from the legacy
        # config; coverage/triple_rate are now soft (recorded, never reject) and
        # the answer gate uses lenient answer_match_score (default min 0.3).
        accept = StratifiedSilverFilter(
            min_steps=silver.min_steps,
            max_steps=silver.max_steps,
        )
        retrieval_top_k = silver.retrieval_top_k
        max_kg_triples = silver.max_kg_triples
        min_kg_keep = silver.min_kg_keep
        bridge_mode = args.bridge_mode or silver.bridge_mode
        bridge_first_round_topk = silver.bridge_first_round_topk
        bridge_max_queries = silver.bridge_max_queries
        bridge_only_k = silver.bridge_only_k
    else:
        if not args.teacher:
            raise SystemExit(
                "--teacher is required when --config is not given (no silent "
                "fallback: retraining_plan §11)."
            )
        teacher_model = args.teacher
        teacher_backend = args.teacher_backend
        temperature = args.temperature
        max_queries = args.max_queries if args.max_queries is not None else 25000
        max_workers = args.max_workers
        out_path = args.output or str(Path(data_dir()) / "silver_data" / "silver_trajectories.jsonl")
        accept = StratifiedSilverFilter()
        retrieval_top_k = DEFAULT_TOPK
        # Same defaults as SilverDataConfig so the two branches cannot drift.
        max_kg_triples = SilverDataConfig.model_fields["max_kg_triples"].default
        min_kg_keep = SilverDataConfig.model_fields["min_kg_keep"].default
        bridge_mode = args.bridge_mode or SilverDataConfig.model_fields["bridge_mode"].default
        bridge_first_round_topk = SilverDataConfig.model_fields[
            "bridge_first_round_topk"
        ].default
        bridge_max_queries = SilverDataConfig.model_fields["bridge_max_queries"].default
        bridge_only_k = SilverDataConfig.model_fields["bridge_only_k"].default

    out_p = Path(out_path)
    if args.resume:
        resume_path = phase1_candidate_path(out_p)
        if not resume_path.exists():
            resume_path = out_p
        items = _load_items(
            args.dataset, args.split, max_queries, resume_path=resume_path,
            sample_strategy=args.sample_strategy, seed=args.seed,
        )
    else:
        items = _load_items(
            args.dataset, args.split, max_queries,
            sample_strategy=args.sample_strategy, seed=args.seed,
        )

    retriever = _build_retriever(args.dataset, topk=retrieval_top_k)

    entity_cache = resolve_entity_cache_path()
    kg_cache_dir = resolve_kg_cache_dir()

    # Decide offline mode. In offline mode, cache misses return empty INSTANTLY
    # instead of blocking on a 10s (entity) / 90s (SPARQL) network timeout each
    # — which would otherwise stretch a 25k run to many hours of pure waiting
    # when Wikidata is unreachable.
    offline = args.offline == "on"
    if args.offline == "auto":
        import requests as _rq

        try:
            _rq.get(
                "https://www.wikidata.org/w/api.php",
                params={"action": "wbsearchentities", "search": "Berlin", "language": "en", "format": "json"},
                headers={"User-Agent": "kgproweight-probe"},
                timeout=8,
            ).raise_for_status()
            offline = False
            logger.info("Wikidata reachable — running ONLINE (cache misses will be fetched live).")
        except Exception as exc:  # noqa: BLE001
            offline = True
            logger.warning(
                "Wikidata UNREACHABLE (%s) — running OFFLINE/cache-only. Cache misses → empty KG "
                "(no per-miss timeout). Entity cache=%s, KG cache=%s.",
                exc, entity_cache, kg_cache_dir,
            )
    else:
        logger.info("Offline mode forced %s by --offline=%s.", "ON" if offline else "OFF", args.offline)

    linker = EntityLinker(cache_path=entity_cache, offline=offline)
    from kgproweight.kg.wikidata_retriever import _QA_RELATION_FILTER

    kg_retr = WikidataSubgraphRetriever(
        max_hops=2, max_neighbors=30, cache_dir=kg_cache_dir, offline=offline,
        relation_filter=_QA_RELATION_FILTER,
    )
    annotator = PRMAnnotator(entity_linker=linker, verbose=False)

    teacher = TeacherClient(
        model=teacher_model,
        backend=teacher_backend,
        temperature=temperature,
    )

    phase_cfg = Phase1Config(
        dataset_name=args.dataset,
        items=items,
        output_path=out_path,
        append_output=args.resume,
        teacher_client=teacher,
        retriever_factory=retriever,
        entity_linker=linker,
        kg_retriever=kg_retr,
        prm_annotator=annotator,
        top_k=retrieval_top_k,
        # Was hardcoded 50, so training.silver_data.max_kg_triples in the YAML
        # was read by nobody (SilverDataConfig has extra="allow", so the key was
        # accepted into model_extra and dropped -- the ppo_max_kg_triples trap).
        max_kg_triples=max_kg_triples,
        min_kg_keep=min_kg_keep,
        rerank_topk=args.rerank,
        bridge_mode=bridge_mode,
        bridge_first_round_topk=bridge_first_round_topk,
        bridge_max_queries=bridge_max_queries,
        bridge_only_k=bridge_only_k,
        max_workers=max_workers,
        accept_filter=accept,
        seed=args.seed,
        teacher_temperature=temperature,
        extra_metadata={
            "source_dataset": args.dataset,
            "source_split": args.split,
            "sample_strategy": args.sample_strategy,
            "sample_seed": args.seed,
            "retrieval_bridge_mode": bridge_mode,
            "retrieval_rrf_candidate_topk": retrieval_top_k,
            "retrieval_rerank_topk": args.rerank,
            "bridge_first_round_topk": bridge_first_round_topk,
            "bridge_max_queries": bridge_max_queries,
            "bridge_only_k": bridge_only_k,
        },
    )
    stats = run_phase1(phase_cfg)
    logger.info("Phase 1 stats: %s", stats)


if __name__ == "__main__":
    main()
